"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../lib/supabase";

type Project = { id:string; user_id:string; title:string; description:string|null; technologies:string[]|null; github_url:string|null; live_url:string|null; created_at:string };

export default function ProjectsPage(){
 const router=useRouter();
 const [projects,setProjects]=useState<Project[]>([]); const [loading,setLoading]=useState(true); const [showForm,setShowForm]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [technologies,setTechnologies]=useState(""); const [githubUrl,setGithubUrl]=useState(""); const [liveUrl,setLiveUrl]=useState("");
 useEffect(()=>{loadProjects();},[]);
 async function user(){const {data:{user}}=await supabase.auth.getUser(); if(!user){router.push("/login");return null;} return user;}
 async function loadProjects(){setLoading(true);const u=await user();if(!u)return;const {data,error}=await supabase.from("projects").select("id,user_id,title,description,technologies,github_url,live_url,created_at").eq("user_id",u.id).order("created_at",{ascending:false});if(error)setError(error.message);else setProjects(data||[]);setLoading(false);}
 async function add(e:FormEvent){e.preventDefault();setError("");if(!title.trim()||!description.trim()){setError("Project title and description are required.");return;}setSaving(true);const u=await user();if(!u){setSaving(false);return;}const {error}=await supabase.from("projects").insert({user_id:u.id,title:title.trim(),description:description.trim(),technologies:technologies.split(",").map(x=>x.trim()).filter(Boolean),github_url:githubUrl.trim()||null,live_url:liveUrl.trim()||null});if(error)setError(error.message);else{setTitle("");setDescription("");setTechnologies("");setGithubUrl("");setLiveUrl("");setShowForm(false);await loadProjects();}setSaving(false);}
 async function remove(id:string){if(!confirm("Delete this project?"))return;const u=await user();if(!u)return;const {error}=await supabase.from("projects").delete().eq("id",id).eq("user_id",u.id);if(error)setError(error.message);else setProjects(p=>p.filter(x=>x.id!==id));}
 const input="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10";
 return <main className="min-h-screen bg-[#f7f9fc] text-slate-900">
  <nav className="sticky top-0 z-20 border-b border-slate-200/80 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><button onClick={()=>router.push("/")} className="text-xl font-black tracking-tight">TECHNERVA<span className="text-blue-600">.</span></button><div className="flex gap-2"><button onClick={()=>router.push("/students")} className="hidden rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 sm:block">Students</button><button onClick={()=>router.push("/dashboard")} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-bold hover:bg-slate-50">Dashboard</button></div></div></nav>
  <section className="mx-auto max-w-6xl px-5 py-12 md:py-16"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-blue-600">Engineering portfolio</p><h1 className="mt-2 text-4xl font-black tracking-tight md:text-5xl">Your projects</h1><p className="mt-4 max-w-2xl text-slate-600">Show the engineering work that proves what you can build.</p></div><button onClick={()=>setShowForm(v=>!v)} className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white shadow-sm hover:bg-blue-700">{showForm?"Close":"+ Add project"}</button></div>
   {error&&<div className="mt-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
   {showForm&&<form onSubmit={add} className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><h2 className="text-xl font-extrabold">Add a project</h2><p className="mt-1 text-sm text-slate-500">Make it easy for another engineer to understand what you built.</p><div className="mt-6 grid gap-5 md:grid-cols-2"><div className="md:col-span-2"><label className="mb-2 block text-sm font-bold">Project title</label><input className={input} value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Campus Connect"/></div><div className="md:col-span-2"><label className="mb-2 block text-sm font-bold">Description</label><textarea className={input+" resize-none"} rows={4} value={description} onChange={e=>setDescription(e.target.value)} placeholder="What problem does it solve and what did you build?"/></div><div><label className="mb-2 block text-sm font-bold">Technologies</label><input className={input} value={technologies} onChange={e=>setTechnologies(e.target.value)} placeholder="Next.js, Supabase, Python"/></div><div><label className="mb-2 block text-sm font-bold">GitHub URL</label><input className={input} type="url" value={githubUrl} onChange={e=>setGithubUrl(e.target.value)} placeholder="https://github.com/..."/></div><div className="md:col-span-2"><label className="mb-2 block text-sm font-bold">Live URL <span className="font-normal text-slate-400">(optional)</span></label><input className={input} type="url" value={liveUrl} onChange={e=>setLiveUrl(e.target.value)} placeholder="https://..."/></div></div><button disabled={saving} className="mt-6 w-full rounded-xl bg-blue-600 py-3.5 font-bold text-white hover:bg-blue-700 disabled:opacity-50">{saving?"Saving…":"Save project"}</button></form>}
   {loading?<div className="mt-10 rounded-2xl border border-slate-200 bg-white p-12 text-center text-slate-500">Loading projects…</div>:projects.length===0&&!showForm?<div className="mt-10 rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-2xl">⌘</div><h2 className="mt-5 text-xl font-extrabold">No projects yet</h2><p className="mx-auto mt-2 max-w-md text-sm text-slate-500">Add your first project to make your engineering profile more credible and discoverable.</p><button onClick={()=>setShowForm(true)} className="mt-5 rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white">Add your first project</button></div>:<div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{projects.map(p=><article key={p.id} className="flex min-h-[250px] flex-col rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-md"><div className="flex items-start justify-between gap-3"><span className="rounded-lg bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700">Project</span><div className="flex gap-1"><button onClick={()=>router.push(`/projects/${p.id}`)} className="rounded-lg px-2.5 py-1.5 text-xs font-bold text-blue-700 hover:bg-blue-50">Edit</button><button onClick={()=>remove(p.id)} className="rounded-lg px-2.5 py-1.5 text-xs font-bold text-slate-500 hover:bg-red-50 hover:text-red-600">Delete</button></div></div><h2 className="mt-5 text-xl font-extrabold">{p.title}</h2><p className="mt-2 line-clamp-4 text-sm leading-6 text-slate-600">{p.description}</p><div className="mt-auto pt-5"><div className="flex flex-wrap gap-2">{(p.technologies||[]).map(t=><span key={t} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{t}</span>)}</div><div className="mt-5 flex gap-4 text-sm font-bold">{p.github_url&&<a href={p.github_url} target="_blank" rel="noreferrer" className="text-slate-700 hover:text-blue-600">GitHub ↗</a>}{p.live_url&&<a href={p.live_url} target="_blank" rel="noreferrer" className="text-blue-600 hover:text-blue-700">Live demo ↗</a>}</div></div></article>)}</div>}
  </section><footer className="border-t border-slate-200 bg-white"><div className="mx-auto max-w-6xl px-5 py-8 text-sm text-slate-500">TECHNERVA — The Engineering Student Network</div></footer>
 </main>;
}