"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

type Profile={id:string;full_name:string;avatar_url:string|null;college:string|null;field_of_study:string|null;course:string|null;specialization:string|null;branch:string|null;graduation_year:number|null;bio:string|null;skills:string[]|null};
type Project={id:string;title:string;description:string|null;technologies:string[]|null;github_url:string|null;live_url:string|null};
type Blog={id:string;title:string;content:string;category:string|null;created_at:string};
type Connection={id:string;requester_id:string;receiver_id:string;status:string};

export default function ProfilePage(){
 const router=useRouter();const {id}=useParams();const profileId=id as string;
 const [profile,setProfile]=useState<Profile|null>(null);const [projects,setProjects]=useState<Project[]>([]);const [blogs,setBlogs]=useState<Blog[]>([]);const [me,setMe]=useState<string|null>(null);const [connection,setConnection]=useState<Connection|null>(null);const [loading,setLoading]=useState(true);const [action,setAction]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{if(profileId)load();},[profileId]);
 async function load(){setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user){router.push("/login");return;}setMe(user.id);const [{data:p,error:pe},{data:ps},{data:bs}]=await Promise.all([supabase.from("profiles").select("id,full_name,avatar_url,college,field_of_study,course,specialization,branch,graduation_year,bio,skills").eq("id",profileId).maybeSingle(),supabase.from("projects").select("id,title,description,technologies,github_url,live_url").eq("user_id",profileId).order("created_at",{ascending:false}),supabase.from("posts").select("id,title,content,category,created_at").eq("user_id",profileId).order("created_at",{ascending:false})]);if(pe){setError(pe.message);setLoading(false);return;}if(!p){setError("Profile not found.");setLoading(false);return;}setProfile(p);setProjects(ps||[]);setBlogs(bs||[]);if(user.id!==profileId){const {data:c}=await supabase.from("connections").select("id,requester_id,receiver_id,status").or(`and(requester_id.eq.${user.id},receiver_id.eq.${profileId}),and(requester_id.eq.${profileId},receiver_id.eq.${user.id})`).maybeSingle();setConnection(c||null);}setLoading(false);}
 async function connect(){if(!me||!profileId||action)return;setAction(true);setError("");const {data,error}=await supabase.from("connections").insert({requester_id:me,receiver_id:profileId,status:"pending"}).select("id,requester_id,receiver_id,status").single();if(error)setError(error.message);else setConnection(data);setAction(false);}
 async function respond(status:"accepted"|"rejected"){if(!connection||action)return;setAction(true);const {data,error}=await supabase.from("connections").update({status}).eq("id",connection.id).select("id,requester_id,receiver_id,status").single();if(error)setError(error.message);else setConnection(data);setAction(false);}
 const own=me===profileId;const incoming=!!connection&&connection.receiver_id===me&&connection.status==="pending";
 if(loading)return <main className="min-h-screen bg-[#f7f9fc] p-8 text-center text-slate-500">Loading profile…</main>;
 if(!profile)return <main className="min-h-screen bg-[#f7f9fc] p-8"><button onClick={()=>router.back()} className="font-bold text-blue-600">← Back</button><div className="mx-auto mt-16 max-w-xl rounded-2xl border border-slate-200 bg-white p-10 text-center">{error||"Profile not found."}</div></main>;
 return <main className="min-h-screen bg-[#f7f9fc] text-slate-900"><nav className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><button onClick={()=>router.push("/")} className="text-xl font-black">TECHNERVA<span className="text-blue-600">.</span></button><div className="flex gap-2"><button onClick={()=>router.push("/students")} className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100">Students</button><button onClick={()=>router.push("/connections")} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-bold hover:bg-slate-50">Connections</button></div></div></nav>
 <section className="mx-auto max-w-6xl px-5 py-10 md:py-14"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-10"><div className="flex flex-col gap-7 md:flex-row md:items-start"><div className="flex h-24 w-24 shrink-0 items-center justify-center overflow-hidden rounded-3xl bg-blue-50 text-3xl font-black text-blue-700">{profile.avatar_url?<img src={profile.avatar_url} alt="" className="h-full w-full object-cover"/>:profile.full_name?.charAt(0).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-blue-600">Engineering profile</p><h1 className="mt-1 text-3xl font-black tracking-tight md:text-4xl">{profile.full_name}</h1><p className="mt-2 text-slate-600">{profile.branch||profile.specialization||profile.course||"Engineering student"}{profile.college?` · ${profile.college}`:""}{profile.graduation_year?` · Class of ${profile.graduation_year}`:""}</p></div>{!own&&<div className="shrink-0">{connection?.status==="accepted"?<span className="inline-flex rounded-xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">✓ Connected</span>:incoming?<div className="flex gap-2"><button disabled={action} onClick={()=>respond("accepted")} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white">Accept</button><button disabled={action} onClick={()=>respond("rejected")} className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold">Decline</button></div>:connection?.status==="pending"?<span className="inline-flex rounded-xl bg-slate-100 px-4 py-3 text-sm font-bold text-slate-600">Request sent</span>:<button disabled={action} onClick={connect} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white hover:bg-blue-700">Connect</button>}</div>}</div><p className="mt-6 max-w-3xl leading-7 text-slate-600">{profile.bio||"Engineering student building projects, learning in public and looking to collaborate."}</p>{profile.skills?.length?<div className="mt-5 flex flex-wrap gap-2">{profile.skills.map(s=><span key={s} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-700">{s}</span>)}</div>:null}</div></div></div>
 {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
 <div className="mt-8 grid gap-8 lg:grid-cols-[1.4fr_.9fr]"><div className="space-y-8"><section><div className="mb-4 flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-[.14em] text-blue-600">Work</p><h2 className="text-2xl font-black">Projects</h2></div><span className="text-sm font-semibold text-slate-400">{projects.length}</span></div>{projects.length?<div className="grid gap-4 md:grid-cols-2">{projects.map(p=><article key={p.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-extrabold">{p.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{p.description}</p><div className="mt-4 flex flex-wrap gap-2">{(p.technologies||[]).map(t=><span key={t} className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700">{t}</span>)}</div><div className="mt-5 flex gap-4 text-sm font-bold">{p.github_url&&<a href={p.github_url} target="_blank" rel="noreferrer" className="text-slate-700 hover:text-blue-600">GitHub ↗</a>}{p.live_url&&<a href={p.live_url} target="_blank" rel="noreferrer" className="text-blue-600">Live ↗</a>}</div></article>)}</div>:<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-sm text-slate-500">No projects added yet.</div>}</section>
 <section><div className="mb-4"><p className="text-sm font-bold uppercase tracking-[.14em] text-blue-600">Writing</p><h2 className="text-2xl font-black">Blogs</h2></div>{blogs.length?<div className="space-y-4">{blogs.map(b=><button key={b.id} onClick={()=>router.push(`/community/${b.id}`)} className="block w-full rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center gap-2 text-xs font-bold text-blue-600">{b.category||"Engineering"} · {new Date(b.created_at).toLocaleDateString()}</div><h3 className="mt-2 text-lg font-extrabold">{b.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-600">{b.content}</p><span className="mt-3 inline-block text-sm font-bold text-blue-600">Read blog →</span></button>)}</div>:<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-sm text-slate-500">No blogs published yet.</div>}</section></div>
 <aside className="space-y-5"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-extrabold">About</h2><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-slate-400">College</dt><dd className="mt-1 font-semibold">{profile.college||"Not added"}</dd></div><div><dt className="text-slate-400">Course</dt><dd className="mt-1 font-semibold">{profile.course||"Engineering"}</dd></div><div><dt className="text-slate-400">Specialization</dt><dd className="mt-1 font-semibold">{profile.specialization||profile.branch||"Not added"}</dd></div></dl></div><div className="rounded-2xl border border-blue-100 bg-blue-50 p-6"><p className="text-sm font-bold text-blue-700">Technerva</p><h2 className="mt-2 text-lg font-extrabold">Build. Share. Connect.</h2><p className="mt-2 text-sm leading-6 text-slate-600">Discover engineering students, their work and the people behind it.</p></div></aside></div></section></main>;
}