"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

type Profile={id:string;full_name:string;avatar_url:string|null;college:string|null;field_of_study:string|null;course:string|null;specialization:string|null;branch:string|null;graduation_year:number|null;bio:string|null;skills:string[]|null};
type Project={id:string;title:string;description:string|null;technologies:string[]|null;github_url:string|null;live_url:string|null};
type Article={id:string;title:string;content:string;category:string|null;created_at:string};

export default function ProfilePage(){
 const router=useRouter(); const params=useParams(); const id=params?.id as string;
 const [profile,setProfile]=useState<Profile|null>(null); const [projects,setProjects]=useState<Project[]>([]); const [articles,setArticles]=useState<Article[]>([]); const [currentUserId,setCurrentUserId]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [notFound,setNotFound]=useState(false);
 useEffect(()=>{if(id)loadProfile();},[id]);
 async function loadProfile(){setLoading(true);setNotFound(false);const {data:{user}}=await supabase.auth.getUser();if(!user){router.push("/login");return;}setCurrentUserId(user.id);
  const {data:profileData,error:profileError}=await supabase.from("profiles").select("id,full_name,avatar_url,college,field_of_study,course,specialization,branch,graduation_year,bio,skills").eq("id",id).maybeSingle();
  if(profileError){console.error("PROFILE ERROR:",profileError);setLoading(false);return;} if(!profileData){setNotFound(true);setLoading(false);return;} setProfile(profileData);
  const [{data:projectData},{data:articleData}]=await Promise.all([supabase.from("projects").select("id,title,description,technologies,github_url,live_url").eq("user_id",id).order("created_at",{ascending:false}),supabase.from("posts").select("id,title,content,category,created_at").eq("user_id",id).order("created_at",{ascending:false})]);
  setProjects(projectData||[]);setArticles(articleData||[]);setLoading(false);
 }
 const isOwnProfile=currentUserId===profile?.id; const completion=useMemo(()=>{if(!profile)return 0;const values=[profile.full_name,profile.avatar_url,profile.college,profile.field_of_study,profile.course,profile.graduation_year,profile.bio,profile.skills?.length];return Math.round(values.filter(Boolean).length/values.length*100)},[profile]);
 if(loading)return <main className="flex min-h-screen items-center justify-center bg-[#050b1f] text-white"><div className="text-center"><div className="mx-auto h-10 w-10 animate-spin rounded-full border-4 border-blue-500/20 border-t-blue-500"/><p className="mt-5 font-semibold text-slate-400">Loading profile...</p></div></main>;
 if(notFound||!profile)return <main className="flex min-h-screen items-center justify-center bg-[#050b1f] px-6 text-white"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[0.04] p-10 text-center"><div className="text-5xl">👤</div><h1 className="mt-6 text-3xl font-black">Profile not found</h1><p className="mt-3 text-slate-400">This student profile doesn't exist or is no longer available.</p><button onClick={()=>router.push("/students")} className="mt-7 w-full rounded-xl bg-blue-600 px-5 py-3.5 font-bold">Back to Students</button></div></main>;
 return <main className="min-h-screen bg-[#050b1f] text-white"><div className="pointer-events-none fixed inset-0 overflow-hidden"><div className="absolute left-[-200px] top-[-150px] h-[600px] w-[600px] rounded-full bg-blue-600/15 blur-[150px]"/><div className="absolute right-[-200px] top-[20%] h-[600px] w-[600px] rounded-full bg-cyan-500/10 blur-[150px]"/></div>
  <nav className="relative z-10 border-b border-white/10 bg-[#050b1f]/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-5 py-5 sm:px-6"><button onClick={()=>router.push("/")} className="text-2xl font-black">Studexa<span className="text-blue-500">.</span></button><div className="flex gap-2 sm:gap-3"><button onClick={()=>router.push("/students")} className="rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2.5 text-sm font-bold text-slate-300">← Students</button>{isOwnProfile&&<button onClick={()=>router.push("/profile/edit")} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold">Edit Profile</button>}</div></div></nav>
  <section className="relative z-10 mx-auto max-w-6xl px-5 py-8 sm:px-6 md:py-14">
   <div className="overflow-hidden rounded-[2rem] border border-white/10 bg-white/[0.045] shadow-2xl backdrop-blur-xl"><div className="h-32 bg-gradient-to-r from-blue-600/30 via-blue-500/10 to-cyan-400/20 sm:h-48"/><div className="relative px-6 pb-8 sm:px-10"><div className="-mt-16">{profile.avatar_url?<img src={profile.avatar_url} alt={profile.full_name} className="h-32 w-32 rounded-3xl border-4 border-[#08102b] object-cover shadow-xl"/>:<div className="flex h-32 w-32 items-center justify-center rounded-3xl border-4 border-[#08102b] bg-blue-500/10 text-5xl font-black text-blue-400">{profile.full_name?.charAt(0).toUpperCase()||"S"}</div>}</div>
    <div className="mt-6 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><h1 className="text-3xl font-black sm:text-5xl">{profile.full_name}</h1><p className="mt-2 text-lg font-semibold text-blue-400">{profile.course||profile.field_of_study||profile.branch||"Student"}</p>{profile.specialization&&<p className="mt-1 text-slate-400">{profile.specialization}</p>}<p className="mt-3 text-slate-400">🎓 {profile.college||"College not added"}</p>{profile.graduation_year&&<p className="mt-2 text-sm text-slate-500">Class of {profile.graduation_year}</p>}</div>{isOwnProfile&&<div className="text-left md:text-right"><p className="text-sm font-bold text-slate-400">Profile completeness</p><p className="mt-1 text-2xl font-black text-blue-400">{completion}%</p></div>}</div>
   </div></div>
   <div className="mt-8 grid gap-6 lg:grid-cols-3"><div className="lg:col-span-2 space-y-6">
    <Card title="ABOUT" heading="About me"><p className="leading-8 whitespace-pre-wrap text-slate-400">{profile.bio||"This student hasn't added a bio yet."}</p></Card>
    <Card title="WORK" heading={`Projects (${projects.length})`}>{projects.length===0?<p className="text-slate-500">No projects added yet.</p>:<div className="space-y-5">{projects.map(p=><div key={p.id} className="rounded-2xl border border-white/10 bg-white/[0.025] p-5"><h3 className="text-xl font-extrabold">{p.title}</h3><p className="mt-2 leading-7 text-slate-400">{p.description||"No description added."}</p>{p.technologies&&<div className="mt-4 flex flex-wrap gap-2">{p.technologies.map(t=><span key={t} className="rounded-full bg-blue-500/10 px-3 py-1.5 text-xs font-bold text-blue-300">{t}</span>)}</div>}<div className="mt-4 flex flex-wrap gap-2">{p.github_url&&<a href={p.github_url} target="_blank" rel="noopener noreferrer" className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm font-bold">GitHub ↗</a>}{p.live_url&&<a href={p.live_url} target="_blank" rel="noopener noreferrer" className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold">Live Demo ↗</a>}</div></div>)}</div>}</Card>
    <Card title="CONTRIBUTIONS" heading={`Articles (${articles.length})`}>{articles.length===0?<p className="text-slate-500">No articles published yet.</p>:<div className="space-y-4">{articles.map(a=><div key={a.id} className="rounded-2xl border border-white/10 bg-white/[0.025] p-5"><div className="flex flex-wrap gap-3"><span className="rounded-full bg-blue-500/10 px-3 py-1 text-xs font-bold text-blue-300">{a.category||"General"}</span><span className="text-xs text-slate-500">{new Date(a.created_at).toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"})}</span></div><h3 className="mt-4 text-xl font-black">{a.title}</h3><p className="mt-2 line-clamp-3 leading-7 text-slate-400">{a.content}</p><button onClick={()=>router.push(`/community/${a.id}`)} className="mt-5 rounded-xl bg-blue-500/10 px-4 py-2.5 text-sm font-bold text-blue-300">Read article →</button></div>)}</div>}</Card>
   </div><div className="space-y-6"><Card title="EXPERTISE" heading="Skills"><div className="flex flex-wrap gap-2.5">{(profile.skills||[]).map(s=><span key={s} className="rounded-xl border border-blue-400/10 bg-blue-500/10 px-3.5 py-2 text-sm font-bold text-blue-300">{s}</span>)}{(!profile.skills||profile.skills.length===0)&&<p className="text-slate-500">No skills added yet.</p>}</div></Card><Card title="ACADEMIC PROFILE" heading="Education"><div className="space-y-5"><Info label="Field" value={profile.field_of_study}/><Info label="Course" value={profile.course}/><Info label="Specialization" value={profile.specialization}/><Info label="Branch / Major" value={profile.branch}/><Info label="College" value={profile.college}/><Info label="Graduation" value={profile.graduation_year?String(profile.graduation_year):null}/></div></Card></div></div>
  </section></main>;
}
function Card({title,heading,children}:{title:string;heading:string;children:React.ReactNode}){return <div className="rounded-3xl border border-white/10 bg-white/[0.045] p-6 shadow-xl backdrop-blur-xl sm:p-8"><p className="text-xs font-extrabold tracking-widest text-blue-400">{title}</p><h2 className="mt-2 text-xl font-black">{heading}</h2><div className="mt-6">{children}</div></div>}
function Info({label,value}:{label:string;value:string|null|undefined}){if(!value)return null;return <div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 font-bold text-slate-200">{value}</p></div>}
