"use client";

import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

type Project={id:string;user_id:string;title:string;description:string|null;technologies:string[]|null;github_url:string|null;live_url:string|null};

export default function EditProjectPage(){const router=useRouter();const {id}=useParams();const [p,setP]=useState<Project|null>(null);const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [tech,setTech]=useState("");const [github,setGithub]=useState("");const [live,setLive]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.push("/login");return;}const {data,error}=await supabase.from("projects").select("id,user_id,title,description,technologies,github_url,live_url").eq("id",id).eq("user_id",user.id).maybeSingle();if(error||!data){setError(error?.message||"Project not found.");setLoading(false);return;}setP(data);setTitle(data.title);setDescription(data.description||"");setTech((data.technologies||[]).join(", "));setGithub(data.github_url||"");setLive(data.live_url||"");setLoading(false);})();},[id,router]);
 async function save(e:FormEvent){e.preventDefault();if(!title.trim()||!description.trim()){setError("Title and description are required.");return;}setSaving(true);const {error}=await supabase.from("projects").update({title:title.trim(),description:description.trim(),technologies:tech.split(",").map(x=>x.trim()).filter(Boolean),github_url:github.trim()||null,live_url:live.trim()||null}).eq("id",p?.id);if(error)setError(error.message);else router.push("/projects");setSaving(false);}
 const input="w-full rounded-xl border border-slate-200 bg-white px-4 py-3.5 text-sm text-slate-900 outline-none placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10";
 if(loading)return <main className="flex min-h-screen items-center justify-center bg-[#f7f9fc] text-slate-500">Loading project…</main>;
 return <main className="min-h-screen bg-[#f7f9fc] text-slate-900"><nav className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-3xl items-center justify-between px-5 py-4"><button onClick={()=>router.push("/")} className="text-xl font-black">TECHNERVA<span className="text-blue-600">.</span></button><button onClick={()=>router.push("/projects")} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-bold hover:bg-slate-50">← Projects</button></div></nav><section className="mx-auto max-w-3xl px-5 py-10 md:py-14"><p className="text-sm font-bold uppercase tracking-[.16em] text-blue-600">Portfolio</p><h1 className="mt-2 text-4xl font-black">Edit project.</h1><p className="mt-3 text-slate-600">Keep your project story clear and useful to other engineers.</p><form onSubmit={save} className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="space-y-5"><div><label className="mb-2 block text-sm font-bold">Project title</label><input className={input} value={title} onChange={e=>setTitle(e.target.value)}/></div><div><label className="mb-2 block text-sm font-bold">Description</label><textarea rows={7} className={input+" resize-none leading-7"} value={description} onChange={e=>setDescription(e.target.value)}/></div><div><label className="mb-2 block text-sm font-bold">Technologies</label><input className={input} value={tech} onChange={e=>setTech(e.target.value)} placeholder="Next.js, TypeScript, Supabase"/></div><div><label className="mb-2 block text-sm font-bold">GitHub URL</label><input type="url" className={input} value={github} onChange={e=>setGithub(e.target.value)} placeholder="https://github.com/..."/></div><div><label className="mb-2 block text-sm font-bold">Live URL <span className="font-normal text-slate-400">(optional)</span></label><input type="url" className={input} value={live} onChange={e=>setLive(e.target.value)} placeholder="https://..."/></div></div>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}<button disabled={saving} className="mt-7 w-full rounded-xl bg-blue-600 py-3.5 font-black text-white hover:bg-blue-700 disabled:opacity-60">{saving?"Saving…":"Save changes →"}</button></form></section></main>;
}