"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../lib/supabase";

const FIELDS = ["All specializations", "Software & Computer Engineering", "Electronics & Communication", "Mechanical Engineering", "Civil Engineering", "Electrical Engineering", "Other Engineering"];

type Student = { id:string; full_name:string; avatar_url:string|null; college:string|null; field_of_study:string|null; course:string|null; specialization:string|null; branch:string|null; graduation_year:number|null; bio:string|null; skills:string[]|null };

export default function StudentsPage() {
  const router = useRouter();
  const [students,setStudents]=useState<Student[]>([]);
  const [search,setSearch]=useState("");
  const [field,setField]=useState("All specializations");
  const [loading,setLoading]=useState(true);

  useEffect(()=>{(async()=>{const {data,error}=await supabase.from("profiles").select("id, full_name, avatar_url, college, field_of_study, course, specialization, branch, graduation_year, bio, skills").order("full_name",{ascending:true}); if(error) console.error("STUDENTS ERROR:",error); else setStudents(data||[]); setLoading(false);})();},[]);

  const filteredStudents=useMemo(()=>students.filter((student)=>{const q=search.toLowerCase().trim(); const specialization=student.specialization||student.branch||""; const matchesField=field==="All specializations"||specialization===field; if(!matchesField)return false; if(!q)return true; const hay=[student.full_name,student.college,student.course,student.specialization,student.branch,...(student.skills||[])].filter(Boolean).join(" ").toLowerCase(); return hay.includes(q);}),[students,search,field]);

  return <main className="min-h-screen bg-slate-50 text-slate-950">
    <nav className="sticky top-0 z-20 border-b border-slate-200 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-6"><button onClick={()=>router.push("/")} className="text-2xl font-black tracking-tight">TECHNERVA<span className="text-blue-600">.</span></button><div className="flex items-center gap-2"><button onClick={()=>router.push("/community")} className="hidden rounded-xl px-4 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-100 md:block">Blogs</button><button onClick={()=>router.push("/connections")} className="hidden rounded-xl px-4 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-100 sm:block">Connections</button><button onClick={()=>router.push("/dashboard")} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white hover:bg-slate-800">Dashboard</button></div></div></nav>
    <section className="technerva-grid mx-auto max-w-7xl px-5 py-12 sm:px-6 md:py-16">
      <div className="max-w-3xl"><div className="inline-flex rounded-full border border-blue-100 bg-blue-50 px-3.5 py-2 text-xs font-extrabold tracking-widest text-blue-700">ENGINEERING NETWORK</div><h1 className="mt-5 text-4xl font-black tracking-tight sm:text-5xl md:text-6xl">Meet the engineers <span className="text-blue-600">building what’s next.</span></h1><p className="mt-5 max-w-2xl text-base leading-8 text-slate-600 sm:text-lg">Discover engineering students by college, branch, skills and interests. Explore their work and connect.</p></div>
      <div className="mt-9 grid max-w-5xl gap-3 md:grid-cols-[1fr_260px]"><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search name, college, branch or skill…" className="rounded-2xl border border-slate-200 bg-white px-5 py-4 text-base outline-none shadow-sm placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-100"/><select value={field} onChange={(e)=>setField(e.target.value)} className="rounded-2xl border border-slate-200 bg-white px-5 py-4 text-slate-800 outline-none shadow-sm focus:border-blue-500 focus:ring-4 focus:ring-blue-100">{FIELDS.map((f)=><option key={f} value={f}>{f}</option>)}</select></div>
      <div className="mt-8 flex items-center justify-between"><p className="text-sm font-bold text-slate-500">{filteredStudents.length} {filteredStudents.length===1?"engineer":"engineers"} found</p>{(search||field!=="All specializations")&&<button onClick={()=>{setSearch("");setField("All specializations")}} className="text-sm font-bold text-blue-600 hover:text-blue-700">Clear filters</button>}</div>
      {loading?<div className="mt-8 rounded-3xl border border-slate-200 bg-white p-12 text-center shadow-sm"><div className="mx-auto h-10 w-10 animate-spin rounded-full border-4 border-blue-100 border-t-blue-600"/><p className="mt-5 font-bold text-slate-500">Finding engineers…</p></div>:filteredStudents.length===0?<div className="mt-8 rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center shadow-sm"><div className="text-4xl">⌕</div><h2 className="mt-5 text-2xl font-black">No engineers found</h2><p className="mt-2 text-slate-500">Try another name, college, branch or skill.</p></div>:<div className="mt-7 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">{filteredStudents.map((student)=><article key={student.id} className="group rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg"><div className="flex items-start justify-between gap-3">{student.avatar_url?<img src={student.avatar_url} alt={student.full_name} className="h-16 w-16 rounded-2xl object-cover"/>:<div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-blue-50 text-xl font-black text-blue-700">{student.full_name?.charAt(0).toUpperCase()||"E"}</div>}{student.graduation_year&&<span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-500">Class of {student.graduation_year}</span>}</div><h2 className="mt-6 text-xl font-black">{student.full_name}</h2><p className="mt-2 font-bold text-blue-600">{student.branch||student.course||"Engineering student"}</p>{student.specialization&&<p className="mt-1 text-sm text-slate-500">{student.specialization}</p>}{student.college&&<p className="mt-3 text-sm font-medium text-slate-500">{student.college}</p>}{student.bio&&<p className="mt-5 line-clamp-3 text-sm leading-6 text-slate-500">{student.bio}</p>}{student.skills&&student.skills.length>0&&<div className="mt-5 flex flex-wrap gap-2">{student.skills.slice(0,4).map((skill)=><span key={skill} className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700">{skill}</span>)}{student.skills.length>4&&<span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-500">+{student.skills.length-4}</span>}</div>}<button onClick={()=>router.push(`/profile/${student.id}`)} className="mt-6 w-full rounded-xl bg-slate-950 px-5 py-3.5 font-bold text-white transition hover:bg-blue-600">View profile</button></article>)}</div>}
    </section>
  </main>;
}
