"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../lib/supabase";

const FIELDS = ["All fields","Engineering","Law","Agriculture","Medicine & Healthcare","Commerce & Management","Arts & Humanities","Science","Design & Architecture","Other"];

type Student = { id:string; full_name:string; avatar_url:string|null; college:string|null; field_of_study:string|null; course:string|null; specialization:string|null; branch:string|null; graduation_year:number|null; bio:string|null; skills:string[]|null };

export default function StudentsPage() {
  const router = useRouter();
  const [students,setStudents]=useState<Student[]>([]); const [search,setSearch]=useState(""); const [field,setField]=useState("All fields"); const [loading,setLoading]=useState(true);

  useEffect(()=>{(async()=>{const {data,error}=await supabase.from("profiles").select("id, full_name, avatar_url, college, field_of_study, course, specialization, branch, graduation_year, bio, skills").order("full_name",{ascending:true}); if(error) console.error("STUDENTS ERROR:",error); else setStudents(data||[]); setLoading(false);})();},[]);

  const filteredStudents=useMemo(()=>students.filter((student)=>{const q=search.toLowerCase().trim(); const matchesField=field==="All fields"||student.field_of_study===field; if(!matchesField)return false; if(!q)return true; const hay=[student.full_name,student.college,student.field_of_study,student.course,student.specialization,student.branch,...(student.skills||[])].filter(Boolean).join(" ").toLowerCase(); return hay.includes(q);}),[students,search,field]);

  return <main className="relative min-h-screen overflow-hidden bg-[#050b24] text-white">
    <div className="pointer-events-none fixed inset-0"><div className="absolute left-[10%] top-[-250px] h-[600px] w-[600px] rounded-full bg-blue-600/15 blur-[150px]"/><div className="absolute right-[-200px] top-[25%] h-[550px] w-[550px] rounded-full bg-cyan-500/10 blur-[150px]"/></div>
    <nav className="relative z-20 border-b border-white/10 bg-[#050b24]/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-6"><button onClick={()=>router.push("/")} className="text-2xl font-black">Studexa<span className="text-blue-500">.</span></button><div className="flex gap-2 sm:gap-3"><button onClick={()=>router.push("/community")} className="hidden rounded-xl px-4 py-2.5 text-sm font-bold text-slate-400 hover:bg-white/[0.05] hover:text-white md:block">Community</button><button onClick={()=>router.push("/dashboard")} className="rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2.5 text-sm font-bold text-slate-300 hover:bg-white/[0.08] hover:text-white">Dashboard</button></div></div></nav>
    <section className="relative z-10 mx-auto max-w-7xl px-5 py-12 sm:px-6 md:py-16">
      <div className="max-w-3xl"><div className="inline-flex rounded-full border border-blue-400/20 bg-blue-500/10 px-3.5 py-2 text-xs font-extrabold tracking-widest text-blue-300">STUDEXA NETWORK</div><h1 className="mt-6 text-4xl font-black sm:text-5xl md:text-6xl">Discover <span className="bg-gradient-to-r from-blue-400 to-cyan-300 bg-clip-text text-transparent">students.</span></h1><p className="mt-5 max-w-2xl text-base leading-8 text-slate-400 sm:text-lg">Find students across engineering, law, agriculture, medicine, commerce, arts, science, design and more.</p></div>
      <div className="mt-9 grid max-w-5xl gap-3 md:grid-cols-[1fr_240px]"><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search name, college, course, skill..." className="rounded-2xl border border-white/10 bg-white/[0.055] px-5 py-4 text-base text-white outline-none placeholder:text-slate-500 focus:border-blue-400/40"/><select value={field} onChange={(e)=>setField(e.target.value)} className="rounded-2xl border border-white/10 bg-[#0a1230] px-5 py-4 text-white outline-none focus:border-blue-400/40">{FIELDS.map((f)=><option key={f} value={f}>{f}</option>)}</select></div>
      <div className="mt-8 flex items-center justify-between"><p className="text-sm font-bold text-slate-500">{filteredStudents.length} {filteredStudents.length===1?"student":"students"} found</p>{(search||field!=="All fields")&&<button onClick={()=>{setSearch("");setField("All fields")}} className="text-sm font-bold text-blue-400 hover:text-blue-300">Clear filters</button>}</div>
      {loading?<div className="mt-8 rounded-3xl border border-white/10 bg-white/[0.045] p-12 text-center"><div className="mx-auto h-10 w-10 animate-spin rounded-full border-4 border-blue-500/20 border-t-blue-500"/><p className="mt-5 font-bold text-slate-400">Finding students...</p></div>:filteredStudents.length===0?<div className="mt-8 rounded-3xl border border-dashed border-white/10 bg-white/[0.035] p-12 text-center"><div className="text-4xl">🔎</div><h2 className="mt-5 text-2xl font-black">No students found</h2><p className="mt-2 text-slate-500">Try another field, course, college or skill.</p></div>:<div className="mt-7 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">{filteredStudents.map((student)=><article key={student.id} className="group relative overflow-hidden rounded-3xl border border-white/10 bg-white/[0.045] p-6 shadow-xl backdrop-blur-xl transition hover:-translate-y-1 hover:border-blue-400/25 hover:bg-white/[0.065]"><div className="flex items-start justify-between gap-3">{student.avatar_url?<img src={student.avatar_url} alt={student.full_name} className="h-16 w-16 rounded-2xl object-cover ring-2 ring-white/10"/>:<div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-500 to-cyan-400 text-xl font-black">{student.full_name?.charAt(0).toUpperCase()||"S"}</div>}{student.graduation_year&&<span className="rounded-full border border-white/10 bg-white/[0.05] px-3 py-1.5 text-xs font-bold text-slate-400">{student.graduation_year}</span>}</div><h2 className="mt-6 text-xl font-black">{student.full_name}</h2><p className="mt-2 font-semibold text-blue-400">{student.course||student.field_of_study||student.branch||"Student"}</p>{student.specialization&&<p className="mt-1 text-sm text-slate-400">{student.specialization}</p>}{student.college&&<p className="mt-3 text-sm text-slate-500">🎓 {student.college}</p>}{student.bio&&<p className="mt-5 line-clamp-3 text-sm leading-6 text-slate-500">{student.bio}</p>}{student.skills&&student.skills.length>0&&<div className="mt-5 flex flex-wrap gap-2">{student.skills.slice(0,4).map((skill)=><span key={skill} className="rounded-full border border-blue-400/15 bg-blue-500/10 px-3 py-1.5 text-xs font-bold text-blue-300">{skill}</span>)}{student.skills.length>4&&<span className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-1.5 text-xs font-bold text-slate-500">+{student.skills.length-4}</span>}</div>}<button onClick={()=>router.push(`/profile/${student.id}`)} className="mt-6 w-full rounded-xl bg-blue-600 px-5 py-3.5 font-bold shadow-lg shadow-blue-600/20 hover:bg-blue-500">View Profile →</button></article>)}</div>}
    </section>
  </main>;
}
