"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../lib/supabase";

type Profile={id:string;full_name:string|null;avatar_url:string|null;college:string|null;branch:string|null;graduation_year:number|null;bio:string|null;skills:string[]|null};
type Project={id:string;title:string;description:string|null;technologies:string[]|null};
type Blog={id:string;title:string;category:string|null;created_at:string};

export default function Dashboard(){
 const router=useRouter();const [profile,setProfile]=useState<Profile|null>(null);const [projects,setProjects]=useState<Project[]>([]);const [blogs,setBlogs]=useState<Blog[]>([]);const [connections,setConnections]=useState(0);const [loading,setLoading]=useState(true);
 useEffect(()=>{load();},[]);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.push("/login");return;}const [{data:p},{data:ps},{data:bs},{count}]=await Promise.all([supabase.from("profiles").select("id,full_name,avatar_url,college,branch,graduation_year,bio,skills").eq("id",user.id).maybeSingle(),supabase.from("projects").select("id,title,description,technologies").eq("user_id",user.id).order("created_at",{ascending:false}).limit(4),supabase.from("posts").select("id,title,category,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(4),supabase.from("connections").select("id",{count:"exact",head:true}).or(`requester_id.eq.${user.id},receiver_id.eq.${user.id}`).eq("status","accepted")]);setProfile(p);setProjects(ps||[]);setBlogs(bs||[]);setConnections(count||0);setLoading(false);}
 async function logout(){await supabase.auth.signOut();router.push("/");}
 if(loading)return <main className="min-h-screen bg-[#f7f9fc] p-10 text-center text-slate-500">Loading dashboard…</main>;
 const completion=[profile?.full_name,profile?.college,profile?.branch,profile?.bio,(profile?.skills?.length?"skills":"")].filter(Boolean).length*20;
 return <main className="min-h-screen bg-[#f7f9fc] text-slate-900"><nav className="sticky top-0 z-20 border-b border-slate-200 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><button onClick={()=>router.push("/")} className="text-xl font-black tracking-tight">TECHNERVA<span className="text-blue-600">.</span></button><div className="flex items-center gap-2"><button onClick={()=>router.push("/students")} className="hidden rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 sm:block">Students</button><button onClick={()=>router.push("/connections")} className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100">Connections</button><button onClick={logout} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-bold hover:bg-slate-50">Log out</button></div></div></nav>
 <section className="mx-auto max-w-6xl px-5 py-10 md:py-14"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-blue-600">Your workspace</p><h1 className="mt-2 text-4xl font-black tracking-tight md:text-5xl">Welcome back{profile?.full_name?`, ${profile.full_name.split(" ")[0]}`:""}.</h1><p className="mt-3 text-slate-600">Build your engineering identity, showcase your work and grow your network.</p></div><button onClick={()=>router.push(profile?`/profile/${profile.id}`:"/profile/setup")} className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white hover:bg-blue-700">View public profile →</button></div>
 <div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">Profile strength</p><p className="mt-2 text-3xl font-black">{completion}%</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${completion}%`}}/></div></div><button onClick={()=>router.push("/projects")} className="rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm hover:shadow-md"><p className="text-sm font-semibold text-slate-500">Projects</p><p className="mt-2 text-3xl font-black">{projects.length}</p><p className="mt-1 text-xs font-bold text-blue-600">Manage projects →</p></button><button onClick={()=>router.push("/connections")} className="rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm hover:shadow-md"><p className="text-sm font-semibold text-slate-500">Connections</p><p className="mt-2 text-3xl font-black">{connections}</p><p className="mt-1 text-xs font-bold text-blue-600">Meet engineers →</p></button></div>
 <div className="mt-8 grid gap-8 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm font-bold uppercase tracking-[.14em] text-blue-600">Your work</p><h2 className="mt-1 text-2xl font-black">Projects</h2></div><button onClick={()=>router.push("/projects")} className="text-sm font-bold text-blue-600">View all</button></div>{projects.length?<div className="mt-5 grid gap-4 sm:grid-cols-2">{projects.map(p=><div key={p.id} className="rounded-xl border border-slate-200 p-5"><h3 className="font-extrabold">{p.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-600">{p.description}</p><div className="mt-4 flex flex-wrap gap-1.5">{(p.technologies||[]).slice(0,4).map(t=><span key={t} className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-600">{t}</span>)}</div></div>)}</div>:<div className="mt-5 rounded-xl border border-dashed border-slate-300 p-8 text-center"><p className="font-bold">Your portfolio starts here.</p><button onClick={()=>router.push("/projects")} className="mt-3 text-sm font-bold text-blue-600">Add your first project →</button></div>}</section>
 <aside className="space-y-5"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-extrabold">Profile</h2><button onClick={()=>router.push("/profile/edit")} className="text-sm font-bold text-blue-600">Edit</button></div><div className="mt-5 flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center overflow-hidden rounded-2xl bg-blue-50 font-black text-blue-700">{profile?.avatar_url?<img src={profile.avatar_url} alt="" className="h-full w-full object-cover"/>:profile?.full_name?.charAt(0)||"E"}</div><div><p className="font-extrabold">{profile?.full_name||"Complete your profile"}</p><p className="text-sm text-slate-500">{profile?.branch||"Engineering student"}</p></div></div><button onClick={()=>router.push("/profile/edit")} className="mt-5 w-full rounded-xl border border-slate-200 py-3 text-sm font-bold hover:bg-slate-50">Edit profile</button></div><div className="rounded-2xl border border-blue-100 bg-blue-50 p-6"><p className="text-sm font-bold text-blue-700">Technerva Blogs</p><h2 className="mt-1 text-lg font-extrabold">Have something worth sharing?</h2><p className="mt-2 text-sm leading-6 text-slate-600">Publish engineering work, project stories and technical insights.</p><button onClick={()=>router.push("/publish-your-works")} className="mt-4 text-sm font-bold text-blue-700">Submit your work →</button></div></aside></div>
 {blogs.length>0&&<section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm font-bold uppercase tracking-[.14em] text-blue-600">Writing</p><h2 className="mt-1 text-2xl font-black">Your blogs</h2></div><button onClick={()=>router.push("/community")} className="text-sm font-bold text-blue-600">Explore community</button></div><div className="mt-5 grid gap-3 md:grid-cols-2">{blogs.map(b=><button key={b.id} onClick={()=>router.push(`/community/${b.id}`)} className="rounded-xl border border-slate-200 p-4 text-left hover:bg-slate-50"><p className="text-xs font-bold text-blue-600">{b.category||"Engineering"}</p><p className="mt-1 font-extrabold">{b.title}</p><p className="mt-1 text-xs text-slate-400">{new Date(b.created_at).toLocaleDateString()}</p></button>)}</div></section>}
 </section></main>;
}